[project]
name = "config-plane"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.8.0",
    "marimo>=0.18.3",
    "pydantic>=2.12.5",
    "pyzmq>=27.1.0",
    "sqlalchemy>=2.0.44",
]
